defaults:
  - _self_
  - optimizer/adamw.yaml

dataset: cifar100
epochs: 10
num_runs: 2
loss_fn:
  _target_: torch.nn.CrossEntropyLoss
conv_layers: 3
lin_layers: 2

hydra:
  run:
    dir: .
  mode: MULTIRUN
  sweeper:
    params:
      +optimizer: adamw-lo, adamw, adamw-hi
      conv_layers: 2, 3, 5, 8, 13
      lin_layers: 2, 3, 4
